syntax = "proto3";

package tle;

import "google/protobuf/timestamp.proto";

option go_package = "gen/tlepb;tlepb";

// Сервис предоставления актуальных TLE спутников
service TleService {

    // Получение TLE по идентификатору спутника
    rpc GetTle (GetTleRequest) returns (GetTleResponse);

    // Получение списка всех доступных TLE
    rpc ListTles (ListTlesRequest) returns (ListTlesResponse);
}


// Двухстрочный набор орбитальных элементов спутника
message Tle {

    // Идентификатор объекта в каталоге NORAD
    uint32 norad_id = 1;

    string satellite_name = 2;

    string line1 = 3;
    string line2 = 4;

    // Эпоха, к которой относятся орбитальные параметры
    google.protobuf.Timestamp epoch = 5;
}


// Идентификатор спутника
message SatelliteIdentifier {
    oneof kind {

        // Идентификатор объекта в каталоге NORAD
        uint32 norad_id = 1;

        string satellite_name = 2;
    }
}


// Запрос на получение TLE
message GetTleRequest {
    SatelliteIdentifier identifier = 1;
}


// Ответ с TLE спутника
message GetTleResponse {
    Tle tle = 1;
}


// Запрос списка TLE
message ListTlesRequest {}


// Ответ со списком TLE
message ListTlesResponse {
    repeated Tle tles = 1;
}