syntax = "proto3";

package user;

import "google/protobuf/timestamp.proto";

option go_package = "gen/userpb;userpb";

// Сервис управления пользователями
service UserService {

    // Создание нового пользователя
    rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);

    // Получение пользователя по идентификатору
    rpc GetUserById (GetUserByIdRequest) returns (GetUserResponse);

    // Получение пользователя по адресу электронной почты
    rpc GetUserByEmail (GetUserByEmailRequest) returns (GetUserResponse);

    // Обновление данных пользователя
    rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);

    // Удаление пользователя
    rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
}

// Информация о пользователе
message User {
    uint32 id = 1;

    string email = 2;

    string username = 3;

    // Хэш пароля пользователя
    string password_hash = 4;

    google.protobuf.Timestamp created_at = 5;

    google.protobuf.Timestamp updated_at = 6;
}

// Запрос на создание пользователя
message CreateUserRequest {
    string email = 1;

    string username = 2;

    string password_hash = 3;
}

// Ответ с созданным пользователем
message CreateUserResponse {
    User user = 1;
}

// Запрос пользователя по идентификатору
message GetUserByIdRequest {
    uint32 id = 1;
}

// Запрос пользователя по электронной почте
message GetUserByEmailRequest {
    string email = 1;
}

// Ответ с данными пользователя
message GetUserResponse {
    User user = 1;
}


// Запрос на обновление пользователя
message UpdateUserRequest {
    uint32 id = 1;

    optional string email = 2;

    optional string username = 3;

    optional string password_hash = 4;
}

// Ответ с обновлёнными данными пользователя
message UpdateUserResponse {
    User user = 1;
}


// Запрос на удаление пользователя
message DeleteUserRequest {
    uint32 id = 1;
}

// Ответ на удаление пользователя
message DeleteUserResponse {}